language: python
branches:
  only:
  - master
services:
- docker
install:
- chmod +x ./scripts/test.sh
- chmod +x ./scripts/publish.sh
script:
- if [[ $TRAVIS_EVENT_TYPE == "pull_request" ]] ; then ./scripts/test.sh ; fi
- if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_BRANCH == "master" ]] ; then ./scripts/publish.sh
  ; fi
notifications:
  slack:
    secure: XPJLuqi3rv1H8xv7AFSHTFw14vEaqwgx9V1FI2VRK+e3Cs9OmdihmzDvuyUmGXM5buzxq3R8ILk5msd9jWXsSSETJYZTXspcrfGwOlvoKlYA8Fop2bGD/FtZMY/ZrjlW38h7m6u+QNtrgKR8ENFLdWseBOyLu0B5u6ci4YEWFg2yMLdtKkkEoonQgKRTyefz+faKYqiECZG9AN2LkkI9UrFDz16VU4t2Ub4/bA8Zu3Fq5T38NI3I3DOPZOHCpg6BLWnpvMZPdezPNn0ynuo38R3rjlclEccq1iVzk6gzzM6JtBGs3ovvj5YWSFdlYsuLCUFX51lniAVgCdjecPbWcpx0zwm2UZRI/p/ou3Ci14dXs3BZVP0FqefL1Bkd4rjDeGtgnMmEi845ihI/V2MDNCvYUrHAGUy5Vu/fj4jWu5HkytEbBRYOIEL9LFtnz3uK0yy9/PbOFuFc64BhyGE04X9X3bM6zL8t1qQIxC/Lt4DEzBpfDYm0kKUQ207130kzwrdlMoJtBYjuzv3KtNs0bqJOZg9uYhnWS5lCe3sEzCHxdOAG8QSHy6fhrXeKQy/RrFfjLuWYbc5h1hCtV2STH1M/jFgORCGblCEvt6BnTj+vMvQFXMpLD/xbfK9VmJ1i8RBnqpsTTgYTJz4SR5DZroMNqumhaGq9WpdWtQBiE78=
